---
title: "SWFSC-CMAP Lab Manual"
page-layout: full
---

## What We Do

The California Current Marine Mammal Assessment Program conducts research on population assessment for species inhabiting waters off the U.S. West Coast, and on improving assessment methodology for application throughout the U.S. and internationally. We provide scientific advice to regional and national policy-makers within NOAA, pursuant to the Marine Mammal Protection Act and Endangered Species Act.

## How to Use this Lab Manual

This lab manual resource is intended to provide an overview for lab members adn others about how we do our work, it serves as a space to document our institutional knowledge, and provides important information about procedures and available resources. If you have suggestions for additions or changes, please contact Shannon (shannon.rankin\@noaa.gov) or Kourtney (kourtney.burger\@noaa.gov), or make a pull request.

## CMAP Team: How to Backup Your Brain
### CMAP Lab Manual
*CATALOG* 
Your one-stop shop to identify and find all CMAP related data and metadata (this manual!)
*Resources*:
*Link to Get Help!, [here](https://cmap-swfsc.github.io/CMAP-SWFSC/#cmap-github-organization-and-lab-manual) (below)*

### Github
*CODE*
Project based repositories (research compendiums, code repositories)
*Resources*: 
[PSAW 2022 R/Github Trainings](https://rverse-tutorials.github.io/PSAW-2022/), specifically the video for an [Intro to Github](https://youtu.be/nNl8KqA57A0?feature=shared) (this is a good approach to using Github)
[NMFS Open Science Resource Book](https://nmfs-opensci.github.io/ResourceBook/)

### Google Cloud (*standby!*)
*Data Archive*
Long term data storage (minimum), will also serve as a working space when virtual machine (vm) is set up.
*Resources*:  standby!

### Google Drive
*NONPUBLIC Data/Metadata*
For data/metadata that must be accessed locally and/or is not to be publicly accessible. Also appropriate for data/metadata for collaborations that do not work well via github and/or cloud. 
*Resources*:
CMAP shared Google Drive [Link Here]()
Instructions for setting up Google Drive for Desktop [Link Here](https://sites.google.com/a/noaa.gov/nmfs-hq-helpdesk/google-drive-for-desktop)


### CMAP Hard Drive (temporary)
External hard drive set up for temporary local use prior to porting to the cloud. Set up on computer (SWC-SWEAV-D) and each team member will have their own folder. We ask that you create folders for each group of materials/topic. Within each folder there should be a 'readme' text file with a basic summary of what is in that folder. 
*Resources*:
When you are ready to backup your data, reach out directly to Kourtney at kourtney.burger\@noaa.gov.



#### Get Help!

You can either email Shannon to get you started, or send us info for each topic following these methods:

1.  **Prep Material**. For each topic, prepare content in format that works for you.

    1.  Create a project summary

    2.  Add other information (as a word doc or similar). Ok to add pictures, etc. We can also do tables.

    3.  Identify all links, pathways (if not online), etc. This can include where this information is stored on the CMAP External Hard drive (the one we are now building).

2.  **Identify info for Public Accessibility. I**f there is any component of this project that you would like to make publicly available, let us know more about this data/code/info (file types, \# files, total size of info, is there any PII?). We can help make this publicly available for you.

3.  **Create a Github Issue.** When all info is complied, Go to the webpage for that topic and create an issue.

    1.  From that specific topic webpage, go to the right hand side of the page, click on the "Report an Issue". Select the green New Issue button (on the right)

    2.  Create a concise but informative title.

    3.  Write a detailed description and include as much info as you can (if this info is saved on a document file, then point us to that document). Provide as much info as you can– what you want on the page itself, links to what is already publicly available, what you want made publicly available, and what you want to retain privately but provide a pathway/link.

    4.  Assign this issue to Shannon, Kourtney, and yourself (if you can). Here is more info on creating an issue.

4.  **Rinse, Repeat.** Do this for each 'Topic' you have, including any side projects (give us a new topic name, and state that they are side projects!). We'll Reach out with any questions!

#### Do it Yourself!

If you want to do it yourself, go for it! If you need to learn, we are happy to help you through it. Here is a basic outline to follow (with links for more info).

1.  **Get Local Access to Repo.** Use Github Desktop and RStudio to get local access to the CMAP-SWFSC repo. [Instructions Link](https://nmfs-ost.github.io/PAM-OpenScience/content/gettingStarted.html) (after you make sure you have the appropriate software, skip down to [Clone Repo to Local Computer](https://nmfs-ost.github.io/PAM-OpenScience/content/gettingStarted.html#clone-repository-to-local-computer)).
2.  **Create and Modify Content.** Instructions provided [here](https://nmfs-ost.github.io/PAM-OpenScience/content/createContent.html).
3.  **Save ancillary documents.** If you have documents (not big file size) that you want to save directly to this Repo, save them in the 'supplemental' folder. To add a link in your webpage file (quarto do), use this format: ***https://github.com/CMAP-SWFSC/CMAP-SWFSC/tree/main/supplement/xxx*** (where xxx is your file name with extension).
4.  **Save related code.** If you have code or rMarkdown docs (not huge) that you want to save directly to the Repo, save them in the 'code' folder. To add a link in your webpage file (quarto do), use this format: ***https://github.com/CMAP-SWFSC/CMAP-SWFSC/tree/main/code/xxx*** (where xxx is your file name with extension).
5.  **Add Smaller Projects.** If you want to add smaller projects (not the bigger topics, there are instructions on the Projects Page.
6.  **Push changes to Github.** When you are finished working on it for the moment, commit & save to github following [these instructions](https://nmfs-ost.github.io/PAM-OpenScience/content/gettingStarted.html#commit-push-to-github).

If you need to make additional repositories for specific projects, feel free to use our github templates to create a [Lab Manual-style Repo](https://nmfs-ost.github.io/PAM-OpenScience/content/labManual.html) (with a website like this!) or our [Research Compendium template](https://nmfs-ost.github.io/PAM-OpenScience/content/researchCompendium.html)(these set you up with less work!). Instructions are provided in the links.

Once you are done, please add an issue, assign to Kourtney/Shannon, and ask us to check it (and also let us know if there are any things you need added, or if you need us to put in links to your other docs).

***As always, reach out if you need help!***
