---
title: Population Risk Assessment
---


## Background
Risk refers to the likelihood and severity of negative outcomes (e.g., of an endangered population not recovering). Our scientists conducts analyses to evaluate risks to marine mammal associated with human stressors or environmental change (e.g., [entanglement risk for large whales](https://www.fisheries.noaa.gov/resource/document/infographic-west-coast-humpback-whale-entanglements)). They communicate risk assessment findings to NOAA managers, and develop tools to help guide decisions for managing risk.

## ObsCovgTools
Assessing the potential risk of fisheries to marine wildlife populations may include an evaluation of observer coverage in terms of how well it documents bycatch of a species of conservation concern (Curtis and Carretta, 2020). The R package [`ObsCovgTools`](https://github.com/kacurtis/ObsCovgTools/tree/main) (Curtis, 2020) provides utilities for evaluating observer coverage with respect to documenting and estimating rare bycatch, including (1) probabilities of observing a bycatch event and of one occurring in total effort, (2) upper confidence limit for bycatch given none was observed, and (3) bycatch estimation CV (coefficient of variation). This tool has generated wide interest, including from ICES, IATTC, MSC, and NOPAT.

The package includes a Shiny web application that is served on the NMFS Posit Connect server at [https://connect.fisheries.noaa.gov/ObsCovg/](https://connect.fisheries.noaa.gov/ObsCovg/) (which requires a Posit Connect account). Login to [Posit Connect](https://connect.fisheries.noaa.gov/) (via single sign-on) provides access to a dashboard with usage statistics and settings for the app deployment. The package version served on Posit Connect must have been built in one of the R versions available on the server. If a Shiny app is no longer working on the Posit Connect server, one of the administrators will typically notify the maintainer of the app, who will need to update the package build to a newer version of R, or otherwise troubleshoot it as needed, and then redeploy it on the server. Resources for Posit Connect users include [NMFS-generated FAQs](https://docs.google.com/document/d/1wWBg_L8vkzTH7kNmJnI2yG4HkVybVo48qWtCrLEei6U/edit#) and a
[Posit Connect demo video](https://drive.google.com/file/d/1SRCn2ANf8SxOMcPsvYuU6LRCaYnvhoZs/view?usp=sharing). Contacts who may be able to provide help with setting up a Posit Connect account and redeploying an app include Kathryn Doering (kathryn.doering@noaa.gov, SWFSC), Sam Woodman (sam.woodman@noaa.gov, SWFSC), and Christine Stawitz (christine.stawitz@noaa.gov, OST). 

The `ObsCovgTools` repository has also been [forked to the SWFSC GitHub Enterprise](https://github.com/SWFSC/ObsCovgTools) organization. 

#### References
Curtis K. A. 2020. ObsCovgTools: Evaluate Fishery Observer Coverage for Bycatch Estimation. R package version 3.1.1. https://kacurtis.github.io/ObsCovgTools

Curtis K. A., Carretta J. V. 2020. ObsCovgTools: Assessing observer coverage needed to document and estimate rare event bycatch. Fisheries Research, 225: 105493. https://doi.org/10.1016/j.fishres.2020.105493
