---
title: Take Reduction Team (TRT) Efforts
---

Take Reduction Plans (TRP) help recover and prevent the depletion of strategic marine mammal stocks that interact with Category I and II fisheries. (Section 118 of the Marine Mammal Protection Act (MMPA) specifies that we develop and implement take reduction plans.)

A strategic stock is one which is:

Listed as endangered or threatened under the Endangered Species Act (ESA). Declining, and likely to be listed as threatened under the ESA. Listed as depleted under the MMPA. Experiencing direct human-caused mortality that exceeds the stock's "Potential Biological Removal (PBR) level." Goals The immediate goal of take reduction plans is to reduce, within six months of its implementation, the incidental mortality or serious injury of marine mammals from commercial fishing to less than the PBR level.

The long-term goal is to reduce, within five years of its implementation, the incidental mortality and serious injury mortality of marine mammals from commercial fishing operations to insignificant levels, approaching a zero mortality and serious injury rate, taking into account the economics of the fishery, the availability of existing technology, and existing state or regional fishery management plans.

Prior TRT-TRP efforts by the Southwest Fisheries Science Center include the [Pacific Offshore TRT-TRP](https://www.fisheries.noaa.gov/national/marine-mammal-protection/pacific-offshore-cetacean-take-reduction-plan)

References:

[Barlow, J. and Cameron, G.A., 2003. Field experiments show that acoustic pingers reduce marine mammal bycatch in the California drift gill net fishery. Marine mammal science, 19(2), pp.265-283.](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1748-7692.2003.tb01108.x)
